In [1]:
import numpy as np

In [42]:
def softmax(x):
    return np.exp(x - np.max(x, axis = 1, keepdims = True)) / np.sum(np.exp(x), axis = 1, keepdims = True)

In [49]:
y = np.random.randn(5,5) #(m,n) m: number of examples, n: example length
print("y =",y)
print("softmax(y) =", softmax(y))
print(np.sum(sy, axis = 1))


y = [[-0.8663067  -0.98352481 -0.03917494  0.70971543 -0.62599753]
 [ 0.13507348  0.54461482 -0.49206764 -0.64670971 -0.40498598]
 [-0.29521866  0.17616622 -0.78273575  0.60459665  0.41750274]
 [ 1.25156974 -0.49538097 -0.28009715 -1.62000872  0.05078459]
 [-0.56165308  0.0629944   0.38729244 -0.0259431   0.05474369]]
softmax(y) = [[0.0478228  0.04253318 0.10935881 0.23125585 0.06081349]
 [0.1421538  0.21410165 0.0759267  0.06504806 0.08283495]
 [0.07080902 0.11345104 0.04348732 0.17412993 0.14441742]
 [0.16364286 0.02852371 0.0353755  0.00926374 0.0492496 ]
 [0.07533645 0.14069741 0.19459288 0.12872445 0.13954133]]
[1. 1. 1. 1. 1.]
