In [1]:
import numpy as np

In [14]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis = 1, keepdims = True)

In [27]:
y = np.random.randn(5,5) #(m,n) m: number of examples, n: example length
print("y =",y)
print("wtf",y[np.arange(5), [1, 2, 3, 0, 4]])
# print("softmax(y) =", softmax(y))


y = [[-0.98485411  0.98100213 -0.08492375 -1.06329111 -0.18430435]
 [-0.7167812  -1.64027361  0.77337243  0.79526511  0.6224124 ]
 [-0.95946221 -0.01939729  0.17024807 -0.19561294 -1.73750317]
 [ 1.12490852 -0.00277518  0.20869036 -0.13066    -1.38229781]
 [ 1.17144407 -0.05725423 -0.8697489  -0.71473789  0.15336207]]
wtf [ 0.98100213  0.77337243 -0.19561294  1.12490852  0.15336207]
